-
  name: 'Login Route'
  uriPattern: 'login/{@action}'
  defaults:
    @package: 'ACL.Tutorial'
    @controller: 'Login'
    @format: 'html'
-
  name: 'Login'
  uriPattern: 'login'
  defaults:
    @package: 'ACL.Tutorial'
    @controller: 'Login'
    @format: 'html'
    @action: 'index'
-
  name: 'Standard Route'
  uriPattern: '{@action}'
  defaults:
    @package: 'ACL.Tutorial'
    @controller: 'Standard'
    @format: 'html'
-
  name: 'Standard'
  uriPattern: ''
  defaults:
    @package: 'ACL.Tutorial'
    @controller: 'Standard'
    @format: 'html'
    @action: 'index'
